// Code generated by "stringer -type DockerCommand"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[START-0]
	_ = x[RESTART-1]
	_ = x[STOP-2]
	_ = x[KILL-3]
	_ = x[PAUSE-4]
	_ = x[UNPAUSE-5]
}

const _DockerCommand_name = "STARTRESTARTSTOPKILLPAUSEUNPAUSE"

var _DockerCommand_index = [...]uint8{0, 5, 12, 16, 20, 25, 32}

func (i DockerCommand) String() string {
	if i < 0 || i >= DockerCommand(len(_DockerCommand_index)-1) {
		return "DockerCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DockerCommand_name[_DockerCommand_index[i]:_DockerCommand_index[i+1]]
}
